//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTickets.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirlineTicketsDBEntities : DbContext
    {
        public AirlineTicketsDBEntities()
            : base("name=AirlineTicketsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<FlightOfferResult> FlightOfferResults { get; set; }
        public virtual DbSet<FlightOfferSearch> FlightOfferSearches { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<FlightsForOffer> FlightsForOffers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
