//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTickets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightOfferSearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightOfferSearch()
        {
            this.FlightOfferResults = new HashSet<FlightOfferResult>();
        }
    
        public int Id { get; set; }
        public int OriginAirportId { get; set; }
        public int DestinationAirportId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public short Adults { get; set; }
        public Nullable<short> Children { get; set; }
        public Nullable<short> Infants { get; set; }
        public Nullable<short> TravelClass { get; set; }
        public Nullable<short> CurrencyCode { get; set; }
        public Nullable<bool> NonStop { get; set; }
        public string URLQuery { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightOfferResult> FlightOfferResults { get; set; }
    }
}
