//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTickets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public int DepartureAirportId { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public int ArrivalAirportId { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string Duration { get; set; }
        public Nullable<short> Order { get; set; }
        public Nullable<int> FlightForOfferId { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        public virtual FlightsForOffer FlightsForOffer { get; set; }
    }
}
