//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTickets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightOfferResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightOfferResult()
        {
            this.FlightsForOffers = new HashSet<FlightsForOffer>();
        }
    
        public int Id { get; set; }
        public int FlightOfferSearchId { get; set; }
        public decimal PriceForAllTravelers { get; set; }
    
        public virtual FlightOfferSearch FlightOfferSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightsForOffer> FlightsForOffers { get; set; }
    }
}
