//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTickets.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightsForOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightsForOffer()
        {
            this.Flights = new HashSet<Flight>();
        }
    
        public int Id { get; set; }
        public int FlightOfferResultId { get; set; }
        public bool IsReturnFlight { get; set; }
        public string Duration { get; set; }
    
        public virtual FlightOfferResult FlightOfferResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
